# pip install pygments mkdocs-material pymdown-extensions
site_name: Bactopia
site_author: Robert A. Petit III
site_description: An extensive workflow to process Illumina sequencing for bacterial genomes.
copyright: "Copyright © 2019-2021 Robert A. Petit III. All rights reserved."

site_url: https://bactopia.github.io/
repo_url: https://github.com/bactopia/bactopia.github.io
google_analytics: ['UA-104199698-2', 'bactopia.github.io']
dev_addr: 0.0.0.0:8000

nav:
    - 'Bactopia':
      - 'Introduction': 'index.md'
      - 'Quick Start': 'quick-start.md'
      - 'Installation': 'installation.md'
      - 'Tutorial': 'tutorial.md'
      - 'Build Datasets': 'datasets.md'
      - 'Basic Usage': 'usage-basic.md'
      - 'Workflow Overview': 'workflow-overview.md'
      - 'Output Overview': 'output-overview.md'
      - 'Complete Usage': 'usage-complete.md'
      - 'Troubleshooting': 'troubleshooting.md'
      - 'Acknowledgements': 'acknowledgements.md'
      - 'Changelog': 'changelog.md'
    - 'Bactopia Tools':
      - 'Introduction': 'bactopia-tools/index.md'
      - 'eggnog': bactopia-tools/eggnog.md
      - 'fastani': bactopia-tools/fastani.md
      - 'gtdb': bactopia-tools/gtdb.md
      - 'hicap': bactopia-tools/hicap.md
      - 'ismapper': bactopia-tools/ismapper.md
      - 'mashtree': bactopia-tools/mashtree.md
      - 'phyloflash': bactopia-tools/phyloflash.md
      - 'pirate': bactopia-tools/pirate.md
      - 'roary': bactopia-tools/roary.md
      - 'staph-typer': bactopia-tools/staph-typer.md
      - 'summary': bactopia-tools/summary.md

theme:
  name: 'material'
  palette:
    scheme: default
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bactopia/bactopia
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/bactopia/Lobby
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/bactopia/bactopia
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rpetit3

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
