# pip install pygments mkdocs-material pymdown-extensions
site_name: Bactopia
site_author: Robert A. Petit III
site_description: An extensive workflow to process Illumina sequencing for bacterial genomes.
copyright: "Copyright © 2019 Robert A. Petit III. All rights reserved."

site_url: https://bactopia.github.io/
repo_url: https://github.com/bactopia/bactopia
google_analytics: ['UA-104199698-2', 'bactopia.github.io']
dev_addr: 0.0.0.0:8000

nav:
    - 'Bactopia':
      - 'Introduction': 'index.md'
      - 'Quick Start': 'quick-start.md'
      - 'Installation': 'installation.md'
      - 'Tutorial': 'tutorial.md'
      - 'Build Datasets': 'datasets.md'
      - 'Basic Usage': 'usage-basic.md'
      - 'Workflow Overview': 'workflow-overview.md'
      - 'Output Overview': 'output-overview.md'
      - 'Complete Usage': 'usage-complete.md'
      - 'Troubleshooting': 'troubleshooting.md'
      - 'Acknowledgements': 'acknowledgements.md'
      - 'Changelog': 'changelog.md'
    - 'Bactopia Tools':
      - 'Introduction': 'bactopia-tools/index.md'
      - 'eggnog': bactopia-tools/eggnog.md
      - 'fastani': bactopia-tools/fastani.md
      - 'gtdb': bactopia-tools/gtdb.md
      - 'ismapper': bactopia-tools/ismapper.md
      - 'mashtree': bactopia-tools/mashtree.md
      - 'phyloflash': bactopia-tools/phyloflash.md
      - 'pirate': bactopia-tools/pirate.md
      - 'roary': bactopia-tools/roary.md
      - 'summary': bactopia-tools/summary.md

theme:
    name: 'material'
    font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
    features:
      - tabs

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - toc:
      permalink: true
